@Library("hdp-utils")
def Utils = new com.puppet.hdp.Utils()

pipeline {
    agent {
      kubernetes {
        defaultContainer 'builder'
        yamlFile 'jenkins/JenkinsKubernetesPod.yaml'
      }
    }
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '30'))
        timeout(time: 25, unit: 'MINUTES', activity: true) //25 minutes of 'inactivity' (no log output)
        ansiColor('xterm')
    }
    environment {
        CI = 'true'
        ARTIFACTORY_SERVER = 'artifactory'
        VERSION = sh(script: "git log -n 1 --pretty=format:'%h'", returnStdout: true).trim()
        GIT_TAG = sh(script: "git describe --always", returnStdout: true).trim()
        GIT_SHA = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
        API_TOKEN = credentials('github-api-token')
        GIT_USER = "puppetlabs-jenkins"
    }
    parameters {
        booleanParam(name: 'DOCKER_CLEANUP', defaultValue: false, description: 'Perform Docker Cleanup at start of run. WARNING: may effect other CI jobs')
    }
    stages {
        stage("PDK Validate 6") {
            steps {
                sh 'pdk validate --puppet-version 6'
            }
        }
        stage("PDK Test 6") {
            steps {
                sh 'pdk test unit --puppet-version 6'
            }
        }
        stage("PDK Validate 7") {
            steps {
                sh 'pdk validate --puppet-version 7'
            }
        }
        stage("PDK Test 7") {
            steps {
                sh 'pdk test unit --puppet-version 7'
                script {
                    Utils.slackNotifyBuild(currentBuild, env)
                }
            }
        }
        stage('Accept') {
            steps {
                script {
                    Utils.pushToTests("module", BRANCH_NAME, GIT_TAG)
                }
            }
        }
    }
}
